language: generic 
sudo: required
services:
  - docker

before-install:
  - docker-build -t TheSaiyan11/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true TheSaiyan11/docker-react npm run test